Added changes

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -23,7 +23,7 @@ jobs:
 
       - name: Create log file
         run: |
-          echo "${{ env.DATE }}" >> log.txt
+          echo "${{ env.DATE }}" > log.txt
           echo "your-username" >> log.txt
 
       - name: Build Docker image
@@ -42,8 +42,9 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: log
+          name: log-build
           path: log.txt
+          overwrite:
 
   test:
     needs: build
@@ -52,7 +53,7 @@ jobs:
       mongo:
         image: mongo:latest
         ports:
-          - 27017:27017
+          - 27018:27017
 
     steps:
       - name: Checkout repository
@@ -67,29 +68,17 @@ jobs:
         run: pip install pytest requests pymongo
 
       - name: Download log from build job
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v2
 
-      - name: Stop and remove any existing containers
+      - name: Start containers
         run: |
-          docker-compose down --volumes
-          docker-compose rm -f
-
-      - name: Run Docker Compose
-        run: docker-compose up -d
+          docker-compose up -d \
+          && echo "Container up and running" >> log.txt \
+          || (echo "Container failed to run" >> log.txt && exit 1)
+        continue-on-error: true
 
       - name: Wait for MongoDB to be ready
-        run: |
-          for i in `seq 1 30`; do
-            nc -z localhost 27017 && echo "MongoDB is up" && break || echo "Waiting for MongoDB..." && sleep 1;
-          done
-
-      # - name: Start containers
-      #   run: |
-      #     docker-compose up -d \
-      #     && echo "Container up and running" >> log.txt \
-      #     || (echo "Container failed to run" >> log.txt && exit 1)
-      #   continue-on-error: true
-
+        run: sleep 30
 
       - name: Run tests
         env:
@@ -115,9 +104,8 @@ jobs:
         if: always() 
         uses: actions/upload-artifact@v4
         with:
-          name: log
+          name: log-test
           path: log.txt
-          overwrite: true 
 
   query:
     needs: test
@@ -126,7 +114,7 @@ jobs:
       mongo:
         image: mongo:latest
         ports:
-          - 27017:27017
+          - 27018:27017
 
     steps:
       - name: Checkout repository
@@ -172,6 +160,7 @@ jobs:
               echo "response: error $HTTP_CODE" >> response.txt
             fi
           done < query.txt
+        continue-on-error: true
 
       - name: Upload response
         if: always()
