Added query.txt

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -36,6 +36,7 @@ jobs:
             echo "image successfully built" >> log.txt
           else
             echo "image not able to be built" >> log.txt
+            exit 1
           fi
 
       - name: Upload Docker image as artifact
@@ -93,7 +94,7 @@ jobs:
 
       - name: Start services 
         run: |
-          docker-compose up -d && echo "Container up and running" >> log.txt || echo "Container failed to run" >> log.txt
+          docker-compose up -d && echo "Container up and running" >> log.txt || (echo "Container failed to run" >> log.txt && exit 1)
 
       - name: List running containers
         run: docker ps
